# Generated by Django 3.2.3 on 2021-05-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_student_graduation_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Factulty',
            new_name='Faculty',
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name_plural': 'certificate'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'department'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'faculty'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name_plural': 'grade'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name_plural': 'school'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'student'},
        ),
    ]
